# DATOS DE CONFIGURACION DE LA APLICACION

# *******************************************************************
# NOMBRE DEL APLICATIVO
app.name=Property-Helper

# DESCRIPCION DEL APLICATIVO
app.descripcion=Modulo de gestion de ficheros properties


