# DATOS DE CONFIGURACIÓN DE LA APLICACIÓN

# *******************************************************************
# NOMBRE DEL APLICATIVO
app.name=Property-Helper

# DESCRIPCIóN DEL APLICATIVO
app.descripcion=Módulo de gestión de ficheros properties



