# DATOS PARA ENVIAR MAIL DESDE LA APLICACIÓN

# *******************************************************************
# DATOS DEL SERVIDOR DE CORREO
mail.smtp.host=servidor
mail.smtp.auth=true
mail.smtp.port=587
mail.smtp.socketFactory.port=587
mail.smtp.ssl.checkserveridentity=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=servidor
mail.smtp.starttls.enable=true

# *******************************************************************
# DATOS DE LA CUENTA UTILIZADA PARA EL ENVÍO DE CORREOS
mail.user=user
mail.password=password
mail.from=from@email.com
mail.to=to@email.com
