# DATOS PARA ENVIAR MAIL DESDE LA APLICACIÓN

# *******************************************************************
# DATOS DEL SERVIDOR DE CORREO
mail.smtp.host=correo.malaga.es
mail.smtp.auth=true
mail.smtp.port=587
mail.smtp.socketFactory.port=587
mail.smtp.ssl.checkserveridentity=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=correo.malaga.es
mail.smtp.starttls.enable=true

# *******************************************************************
# DATOS DE LA CUENTA UTILIZADA PARA EL ENVÍO DE CORREOS
mail.user=incidenciascontratacion@malaga.es
mail.password=BWFZHGPIJKXVNSLU
mail.from=incidenicascontratacion@malaga.es
mail.to=jarios@malaga.es
