name: Java CI with Maven

on:
  push:
    branches:
      - main    # O la rama que uses por defecto
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify

      - name: Quality checks
        run: mvn -Pquality verify

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'properties-helper'
          scanPath: '.'
